blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://onflow.org/discord
  - name: Github Discussions
    url: https://github.com/orgs/onflow/discussions
  - name: Flow Forums
    url: https://forum.onflow.org
